[package]
name = "knightwatch-tui"
version = "1.0.0"
edition = "2024"
authors = ["YofaGh"]
description = "TUI client for Knightwatch"
homepage = "https://github.com/YofaGh/knightwatch"
repository = "https://github.com/YofaGh/knightwatch"
license = "MIT"

[[bin]]
name = "kwtui"
path = "src/main.rs"

[dependencies]
base64 = { workspace = true }
crossterm = { version = "0.29.0", features = ["event-stream"] }
futures = { workspace = true }
ratatui = { version = "0.30.2", features = ["crossterm"] }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
ratatui-image = { version = "11.0.6", default-features = false, features = [
    "crossterm",
] }
image = "0.25.10"
kw-clients = { path = "../kw-clients" }
kw-types = { path = "../kw-types" }
kw-utils = { path = "../kw-utils" }

[lints]
workspace = true
