[package]
name = "dashboard-frontend"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
knightwatch = { path = "../server", default-features = false, features = [
    "hydrate",
] }

[package.metadata.wasm-pack.profile.release]
wasm-opt = ["-Oz", "--strip-debug", "--strip-producers", "--enable-bulk-memory"]