[workspace]
resolver = "2"
members = ["server", "dashboard-frontend"]

[profile.release]
opt-level = 'z'
lto = true
codegen-units = 1
panic = 'abort'
strip = true
debug = false
overflow-checks = false

# Force all dependencies to also compile at opt-level z
# By default deps compile at opt-level 3 even in a release profile
[profile.release.package."*"]
opt-level = 'z'

# cargo-leptos uses this profile for the WASM bundle
[profile.wasm-release]
inherits = "release"
opt-level = 'z'
lto = true
codegen-units = 1
panic = 'abort'
strip = true
debug = false
overflow-checks = false

[[workspace.metadata.leptos]]
name = "knightwatch"
bin-package = "knightwatch"
bin-features = ["ssr"]
lib-package = "dashboard-frontend"
site-root = "target/site"
site-pkg-dir = "pkg"
assets-dir = "public"
site-addr = "127.0.0.1:3000"
reload-port = 3001