[package]
name = "kw-clients"
version = "1.0.2"
edition = "2024"
authors.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
futures = { workspace = true }
reqwest = { workspace = true, features = ["json", "stream"] }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
kw-types = { path = "../kw-types" }
eventsource-stream = "0.2.3"

[lints]
workspace = true
