name: Release knightwatch

on:
  push:
    tags:
      - 'knightwatch/[0-9]*.[0-9]*.[0-9]*'

permissions:
  contents: write

jobs:
  release:
    uses: ./.github/workflows/_release.yml
    with:
      package: knightwatch
      bin_name: knightwatch
      linux_extra_deps: "libwayland-dev libpipewire-0.3-dev libegl-dev libgbm-dev"
      build_msi: true
      build_headless: true
      bundle_helper: true
      homebrew_class: Knightwatch
      homebrew_desc: "System Monitoring tool"
      latest: true
    secrets: inherit
